package singleserver

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func overlayTestGenerated(t *testing.T, app AppConfig) []byte {
	t.Helper()
	t.Setenv("SINGLESERVER_STATE_DIR", t.TempDir())
	body, err := GeneratedDeployYAML(app)
	if err != nil {
		t.Fatal(err)
	}
	return body
}

func mergeOverlayForTest(t *testing.T, generated []byte, overlay string) map[string]any {
	t.Helper()
	merged, err := mergeDeployOverlay(generated, []byte(overlay))
	if err != nil {
		t.Fatal(err)
	}
	var config map[string]any
	if err := yaml.Unmarshal(merged, &config); err != nil {
		t.Fatal(err)
	}
	return config
}

func topLevelKeys(t *testing.T, body []byte) []string {
	t.Helper()
	var doc yaml.Node
	if err := yaml.Unmarshal(body, &doc); err != nil {
		t.Fatal(err)
	}
	keys := []string{}
	for i := 0; i < len(doc.Content[0].Content); i += 2 {
		keys = append(keys, doc.Content[0].Content[i].Value)
	}
	return keys
}

func TestMergeDeployOverlayEmptyOverlayKeepsGeneratedBytes(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard", SecretEnvKeys: []string{"DATABASE_URL"}})

	for _, overlay := range []string{"", "\n", "# nothing yet\n", "~\n"} {
		merged, err := mergeDeployOverlay(generated, []byte(overlay))
		if err != nil {
			t.Fatalf("overlay %q: %v", overlay, err)
		}
		if !bytes.Equal(merged, generated) {
			t.Fatalf("overlay %q changed the generated config:\n%s", overlay, merged)
		}
	}
}

func TestMergeDeployOverlayRoundTripIsByteStable(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{
		Repo:          "acme/scoreboard",
		Hosts:         []string{"scoreboard.example.com"},
		SecretEnvKeys: []string{"DATABASE_URL"},
		Storage:       &StorageConfig{Path: "/srv/storage/scoreboard", Mount: "/storage"},
	})

	merged, err := mergeDeployOverlay(generated, []byte("deploy_timeout: 10\n"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(merged, generated) {
		t.Fatalf("expected a no-op overlay to keep the generated bytes, got:\n%s\nwant:\n%s", merged, generated)
	}
}

func TestMergeDeployOverlayAppendsNewTopLevelKeysAfterGeneratedOnes(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard"})

	merged, err := mergeDeployOverlay(generated, []byte("boot:\n  limit: 1\n"))
	if err != nil {
		t.Fatal(err)
	}
	generatedKeys := topLevelKeys(t, generated)
	mergedKeys := topLevelKeys(t, merged)
	want := append(append([]string{}, generatedKeys...), "boot")
	if strings.Join(mergedKeys, ",") != strings.Join(want, ",") {
		t.Fatalf("unexpected key order: %v, want %v", mergedKeys, want)
	}
}

func TestMergeDeployOverlayEnvClearKeepsGeneratedSecrets(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard", SecretEnvKeys: []string{"DATABASE_URL", "STRIPE_KEY"}})

	config := mergeOverlayForTest(t, generated, "env:\n  clear:\n    LOG_LEVEL: debug\n")

	env := config["env"].(map[string]any)
	secrets := env["secret"].([]any)
	if len(secrets) != 2 || secrets[0] != "DATABASE_URL" || secrets[1] != "STRIPE_KEY" {
		t.Fatalf("expected generated secrets to survive, got %#v", secrets)
	}
	clear := env["clear"].(map[string]any)
	if clear["LOG_LEVEL"] != "debug" {
		t.Fatalf("expected overlay clear env, got %#v", clear)
	}
}

func TestMergeDeployOverlayAddsEnvWhenGeneratedHasNone(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard"})

	config := mergeOverlayForTest(t, generated, "env:\n  clear:\n    LOG_LEVEL: debug\n")

	env := config["env"].(map[string]any)
	if _, ok := env["secret"]; ok {
		t.Fatalf("expected no secrets, got %#v", env)
	}
	if env["clear"].(map[string]any)["LOG_LEVEL"] != "debug" {
		t.Fatalf("expected overlay clear env, got %#v", env)
	}
}

func TestMergeDeployOverlayMergesMappingsAndReplacesScalarsAndSequences(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{
		Repo:    "acme/scoreboard",
		Hosts:   []string{"scoreboard.example.com"},
		Storage: &StorageConfig{Path: "/srv/storage/scoreboard", Mount: "/storage"},
	})

	config := mergeOverlayForTest(t, generated, strings.Join([]string{
		"volumes:",
		"  - /srv/cache:/cache",
		"proxy:",
		"  response_timeout: 60",
		"  healthcheck:",
		"    interval: 5",
		"",
	}, "\n"))

	volumes := config["volumes"].([]any)
	if len(volumes) != 1 || volumes[0] != "/srv/cache:/cache" {
		t.Fatalf("expected overlay volumes to replace generated ones, got %#v", volumes)
	}
	proxy := config["proxy"].(map[string]any)
	if proxy["response_timeout"] != 60 {
		t.Fatalf("expected new proxy key, got %#v", proxy)
	}
	if proxy["app_port"] != 80 || proxy["forward_headers"] != true {
		t.Fatalf("expected generated proxy keys to survive, got %#v", proxy)
	}
	hosts := proxy["hosts"].([]any)
	if len(hosts) != 1 || hosts[0] != "scoreboard.example.com" {
		t.Fatalf("expected generated proxy hosts, got %#v", hosts)
	}
	healthcheck := proxy["healthcheck"].(map[string]any)
	if healthcheck["interval"] != 5 || healthcheck["path"] != "/" || healthcheck["timeout"] != 1 {
		t.Fatalf("unexpected healthcheck: %#v", healthcheck)
	}
}

func TestMergeDeployOverlayResolvesAliases(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard"})

	merged, err := mergeDeployOverlay(generated, []byte("x-tag: &tag scoreboard\nlogging:\n  options:\n    tag: *tag\n"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(merged), "*tag") || strings.Contains(string(merged), "&tag") {
		t.Fatalf("expected aliases to be resolved, got:\n%s", merged)
	}
	var config map[string]any
	if err := yaml.Unmarshal(merged, &config); err != nil {
		t.Fatal(err)
	}
	if config["logging"].(map[string]any)["options"].(map[string]any)["tag"] != "scoreboard" {
		t.Fatalf("unexpected logging: %#v", config["logging"])
	}
}

func TestMergeDeployOverlayRejectsManagedKeys(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard"})

	for _, key := range []string{"service", "image", "servers", "ssh", "registry"} {
		_, err := mergeDeployOverlay(generated, []byte(key+": anything\n"))
		if err == nil {
			t.Fatalf("expected %s to be rejected", key)
		}
		if !strings.Contains(err.Error(), `"`+key+`"`) || !strings.Contains(err.Error(), deployOverlayPath) {
			t.Fatalf("expected error naming %s and the overlay, got %v", key, err)
		}
	}
}

func TestMergeDeployOverlayRejectsInvalidYAMLAndNonMappings(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard"})

	for _, overlay := range []string{"logging: [unclosed\n", "- logging\n", "just a string\n"} {
		if _, err := mergeDeployOverlay(generated, []byte(overlay)); err == nil {
			t.Fatalf("expected overlay %q to be rejected", overlay)
		}
	}
}

func commitOverlayTestRepo(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for path, body := range files {
		full := filepath.Join(dir, path)
		if err := os.MkdirAll(filepath.Dir(full), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(body), 0644); err != nil {
			t.Fatal(err)
		}
	}
	for _, args := range [][]string{
		{"init", "-q"},
		{"add", "-A"},
		{"-c", "user.name=test", "-c", "user.email=test@example.com", "commit", "-q", "-m", "init"},
	} {
		cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("git %v: %v\n%s", args, err, out)
		}
	}
}

func overlayTestApp(t *testing.T, files map[string]string) AppConfig {
	t.Helper()
	dir := t.TempDir()
	t.Setenv("SINGLESERVER_STATE_DIR", dir)
	repoDir := filepath.Join(dir, "repo")
	if err := os.MkdirAll(repoDir, 0755); err != nil {
		t.Fatal(err)
	}
	commitOverlayTestRepo(t, repoDir, files)
	return AppConfig{Repo: "acme/scoreboard", Name: "scoreboard", RepoDir: repoDir}
}

func TestDeployYAMLForCheckoutAppliesTrackedOverlay(t *testing.T) {
	app := overlayTestApp(t, map[string]string{
		deployOverlayPath: "boot:\n  limit: 1\n",
	})

	body, source, err := deployYAMLForCheckout(app)
	if err != nil {
		t.Fatal(err)
	}
	if source != "generated + repo overlay .singleserver/deploy.yml" {
		t.Fatalf("unexpected source: %q", source)
	}
	if !strings.Contains(string(body), "boot:\n  limit: 1\n") {
		t.Fatalf("expected overlay in config, got:\n%s", body)
	}
}

func TestDeployYAMLForCheckoutIgnoresUntrackedOverlay(t *testing.T) {
	app := overlayTestApp(t, map[string]string{"README.md": "hi\n"})
	if err := os.MkdirAll(filepath.Join(app.RepoDir, ".singleserver"), 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(app.RepoDir, deployOverlayPath), []byte("servers: nope\n"), 0644); err != nil {
		t.Fatal(err)
	}

	body, source, err := deployYAMLForCheckout(app)
	if err != nil {
		t.Fatal(err)
	}
	generated, err := GeneratedDeployYAML(app)
	if err != nil {
		t.Fatal(err)
	}
	if source != "generated from conventions" || !bytes.Equal(body, generated) {
		t.Fatalf("expected untracked overlay to be ignored, got %q:\n%s", source, body)
	}
}

func TestDeployYAMLForCheckoutRepoConfigWinsOverOverlay(t *testing.T) {
	app := overlayTestApp(t, map[string]string{
		repoDeployConfigPath: "service: custom\n",
		deployOverlayPath:    "servers: nope\n",
	})

	_, source, err := deployYAMLForCheckout(app)
	if err != nil {
		t.Fatal(err)
	}
	if source != "generated from conventions" {
		t.Fatalf("expected overlay to be skipped when config/deploy.yml is tracked, got %q", source)
	}
}

func TestDoctorDeployConfigReportsOverlay(t *testing.T) {
	app := overlayTestApp(t, map[string]string{deployOverlayPath: "boot:\n  limit: 1\n"})

	var out bytes.Buffer
	if !doctorDeployConfig(&out, app) {
		t.Fatalf("expected overlay to pass, got:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "scoreboard\tdeploy_config\tok\tgenerated + repo overlay .singleserver/deploy.yml") {
		t.Fatalf("unexpected doctor output:\n%s", out.String())
	}
}

func TestDoctorDeployConfigFailsOnManagedKeyInOverlay(t *testing.T) {
	app := overlayTestApp(t, map[string]string{deployOverlayPath: "service: other\n"})

	var out bytes.Buffer
	if doctorDeployConfig(&out, app) {
		t.Fatalf("expected managed key to fail, got:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "scoreboard\tdeploy_config\tfailed") || !strings.Contains(out.String(), `"service"`) {
		t.Fatalf("unexpected doctor output:\n%s", out.String())
	}
}

func TestDoctorDeployConfigFailsOnInvalidOverlayYAML(t *testing.T) {
	app := overlayTestApp(t, map[string]string{deployOverlayPath: "logging: [unclosed\n"})

	var out bytes.Buffer
	if doctorDeployConfig(&out, app) {
		t.Fatalf("expected invalid overlay to fail, got:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "scoreboard\tdeploy_config\tfailed\t.singleserver/deploy.yml") {
		t.Fatalf("unexpected doctor output:\n%s", out.String())
	}
}

func TestInspectPrintsMergedOverlay(t *testing.T) {
	app := overlayTestApp(t, map[string]string{
		deployOverlayPath: "logging:\n  driver: journald\n  options:\n    tag: scoreboard\n",
	})
	configPath := filepath.Join(os.Getenv("SINGLESERVER_STATE_DIR"), "apps.yml")
	t.Setenv("SINGLESERVER_CONFIG", configPath)
	apps := "apps:\n  - repo: acme/scoreboard\n    path: " + app.RepoDir + "\n"
	if err := os.WriteFile(configPath, []byte(apps), 0600); err != nil {
		t.Fatal(err)
	}

	var out bytes.Buffer
	if err := cliInspect([]string{"scoreboard"}, &out); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(out.String(), "logging:\n  driver: journald\n  options:\n    tag: scoreboard\n") {
		t.Fatalf("expected merged logging, got:\n%s", out.String())
	}
	if !strings.HasPrefix(out.String(), "service: scoreboard\nimage: scoreboard\n") {
		t.Fatalf("expected generated keys first, got:\n%s", out.String())
	}
}

func TestMergeDeployConfigCommandWritesMergedFile(t *testing.T) {
	dir := t.TempDir()
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard"})
	t.Setenv(generatedDeployYAMLEnv, string(generated))
	overlayPath := filepath.Join(dir, "overlay.yml")
	outputPath := filepath.Join(dir, "deploy.yml")
	if err := os.WriteFile(overlayPath, []byte("boot:\n  limit: 1\n"), 0644); err != nil {
		t.Fatal(err)
	}

	if err := runCLI([]string{mergeDeployConfigCommand, overlayPath, outputPath}, nil, &bytes.Buffer{}); err != nil {
		t.Fatal(err)
	}
	body, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(body), string(generated)) || !strings.HasSuffix(string(body), "boot:\n  limit: 1\n") {
		t.Fatalf("unexpected merged file:\n%s", body)
	}

	if err := os.WriteFile(overlayPath, []byte("registry: {}\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := runCLI([]string{mergeDeployConfigCommand, overlayPath, outputPath}, nil, &bytes.Buffer{}); err == nil {
		t.Fatal("expected managed key to fail the merge command")
	}
}

func TestMergeDeployOverlayOverridesDefaultLogging(t *testing.T) {
	generated := overlayTestGenerated(t, AppConfig{Repo: "acme/scoreboard"})

	config := mergeOverlayForTest(t, generated, "logging:\n  driver: json-file\n  options:\n    max-size: 10m\n")

	logging := config["logging"].(map[string]any)
	if logging["driver"] != "json-file" {
		t.Fatalf("expected overlay driver, got %#v", logging)
	}
	options := logging["options"].(map[string]any)
	if options["max-size"] != "10m" || options["tag"] != "scoreboard" {
		t.Fatalf("expected overlay options merged over the default tag, got %#v", options)
	}
}
